### ISSUE TITLE
可以用在多个音乐播放设备上吗

### ISSUE THREAD

**Issue by MageDelfador** [shaonianzhentan/ha_cloud_music#3]
设置了一下，发现好像只能使用一个播放设备。请教一下多个播放设备如何使用云音乐？

**Comment by shaonianzhentan** [comment]
你的使用场景是什么？

**Comment by MageDelfador** [comment]
谢谢回复。卫生间、厨房各有一个顶部安装的音箱，还有一些可以移动的播放设备。我在customize.yaml里像这样配置
 ```
media_player.yun_yin_le: 
     media_player: media_player.wmusic 
```
这样似乎只能使用单个设备，不能满足不同场景下不同设备的播放。

**Comment by shaonianzhentan** [comment]
已支持配置多个播放器
```yaml
media_player.yun_yin_le: 
    media_player: 
       - media_player.wmusic1
       - media_player.wmusic2
```
