### ISSUE TITLE
部分小爱音箱不能播放可以升级 hass-xiaomi-miot试试

### ISSUE THREAD

**Issue by hanxi** [shaonianzhentan/ha_cloud_music#56]
具体见 <https://github.com/al-one/hass-xiaomi-miot/pull/1756>

**Comment by al-one** [comment]
[media_player.play_media](https://my.home-assistant.io/redirect/developer_call_service/?service=media_player.play_media)
```yaml
service: media_player.play_media
data:
  entity_id: media_player.xiaoai_x08c_d135
  media_content_id: https://cdn1.suno.ai/8830d063-71a4-4f02-8855-6aa3008899a7.mp3
  media_content_type: music
```
